[aws]
format = 'on [$symbol ($profile )]($style)'
symbol = ""
#disabled = true
[aws.region_aliases]
eu-west-1 = 'eu'
us-east-1 = 'na'
cn-northwest-1 = 'cn'

[java]
disabled=true

[package]
disabled=true

[python]
disabled=true

