
[terminal.shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/bin/bash"

[window]
#decorations = "None"
startup_mode = "Maximized"
dynamic_padding = false
opacity = 0.9

[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[terminal]
